name: YAAY
version: ${project.version}
main: io.josemmo.bukkit.plugin.addon.imgui.ImguiAddonPlugin
api-version: 1.16
folia-supported: true
libraries:
  - org.xerial:sqlite-jdbc:3.46.1.3
depend: [YamipaPlugin]
description: "Yes, Another Addon for Yamipa"

commands:
  imgui:
    description: Open image claim GUI
    usage: /imgui [reload]

permissions:
  yamipa.imgui.use:
    default: true
  yamipa.imgui.reload:
    default: op
